### ISSUE TITLE
Lists queried incorrectly 

### ISSUE THREAD

**Issue by scholl3ss** [heroku/heroku.jar#79]
compare to: https://devcenter.heroku.com/articles/platform-api-reference#ranges
e.g. AppList queries apps and if there are more than 200 apps the returned status code will be 206, 
which will throw an error because the only accepted value is 200.

**Comment by jkutner** [comment]
I can fix that pretty easily, but I probably also need to handle the `Next-Range` stuff. So It might take a bit to fix. Thanks.

**Comment by jkutner** [comment]
To be fixed by 187473767b273394fd65ff1359aaab9c9465cf29

**Comment by scholl3ss** [comment]
Fyi: heroku's App list api is broken as well, but I did not figure out how to report it as it is not security relevant probably.
Setting range header to "Name ..; max=1" will stop serving a next-content after 3 responses, altough Status Code is 206.

**Comment by scholl3ss** [comment]
Altough Sorting with id or updated_at works as expected

**Comment by jkutner** [comment]
This is available in 0.21. You can do the following:

```java
Range<App> apps = api.listApps();
Range<App> moreApps = api.listApps(apps.getNextRange());
```

In hindsight, the `Range` class should probably have a method like `hasMore` or something. For now I think you'll have to check for `null` :(

**Comment by scholl3ss** [comment]
Thank you. 
Can you confirm the Bug in the api? This is not wrapper related.

**Comment by jkutner** [comment]
@scholl3ss I'm not sure about the underlying service. Can you open a ticket at https://help.heroku.com ?
