### ISSUE TITLE
Scaling support

### ISSUE THREAD

**Issue by rosogon** [heroku/heroku.jar#80]
Hi,

As of https://github.com/heroku/heroku.jar/commit/567f98b4ed8949ecbdec285f211f978810b5a00c, the support for scaling and restart was removed. Is there any plan to add the support again?

**Comment by jkutner** [comment]
Yes, we will add this back in soon. The old version of the lib used API v2, which has been deprecated and shutdown. I'll need to update it to use the API v3 [Dyno Restart](https://devcenter.heroku.com/articles/platform-api-reference#dyno-restart) and [Formation Batch Update (Scaling)](https://devcenter.heroku.com/articles/platform-api-reference#formation-batch-update endpoints.

**Comment by rosogon** [comment]
I created a Scale request (similar to the old Scale.java, but using new Formation resource) and it looks it works. If you have done nothing yet, I can maybe help with a pull request.

**Comment by jkutner** [comment]
@rosogon i would very welcome a PR. I've already started the Dyno Restart (and Listing) though. But having the Formation request would help.

**Comment by rosogon** [comment]
Hi, @jkutner. I guess this can be closed.
