### ISSUE TITLE
Provide ability to configure addon at creation time

### ISSUE THREAD

**Issue by tomdcc** [heroku/heroku.jar#83]
Currently, we use the `AddonInstall` object to represent our addon creation requests. It is not currently possible to pass extra config to this object to represent configuration of that addon, e.g. [postgres version](https://github.com/heroku/platform-api/issues/80#issuecomment-319111748).

It should be possible to pass in a `Map<String, Object>` of configuration options for addons that are created.

**Comment by jkutner** [comment]
@tomdcc thanks for reporting this. that definitely seems like something we can add.

**Comment by jkutner** [comment]
@tomdcc I wanted to let you know I'm still working on this. I've run into a little problem with my automated tests getting rate-limited by the API. I'm trying to sort that out before publishing anything. Thanks for you patience.

**Comment by jkutner** [comment]
@tomdcc this will be available in 0.32

**Comment by tomdcc** [comment]
@jkutner Great, thanks!
