### ISSUE TITLE
Teams support

### ISSUE THREAD

**Issue by aslakagens** [heroku/heroku.jar#87]
Will this API support Teams in the future?

**Comment by aslakagens** [comment]
The following endpoints would be very useful:

GET /teams/apps/{team_app_name}
GET /teams/{team_name_or_id}/apps
POST /teams/apps

GET /teams/{team_name_or_id}/invoices/{team_invoice_number}
GET /teams/{team_name_or_id}/invoices

**Comment by jkutner** [comment]
I'm working on this in https://github.com/heroku/heroku.jar/tree/teams

**Comment by jkutner** [comment]
@aslakagens this should be available in version 0.34 through the following methods:

* `HerokuAPI.getTeamApp(String)`
* `HerokuAPI.listTeamApps(String)`
* `HerokuAPI.listTeamApps(String, String)`
* `HerokuAPI.listTeamInvoices(String)`
* `HerokuAPI.listTeamInvoices(String, String)`

Please let us know if you have any issues.

**Comment by aslakagens** [comment]
Thanks. Looks great. How about createTeamApp?

**Comment by jkutner** [comment]
@aslakagens ah, i missed that one. Yes, we'll add that soon.

**Comment by aslakagens** [comment]
Great. Thanks

**Comment by jkutner** [comment]
@aslakagens the following methods are available in version 0.35.

* `createTeam(String)`
* `createTeamApp(String)`
* `createTeamApp(String,TeamApp)`

I'm going to close this issue, but feel free to reopen if you have issues.
